### ISSUE TITLE
Quota for each project on the user dashboard

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tigerdata-app#1030]
Figma link - https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=807-2898&node-type=frame&m=dev

We need a quota widget to display for each project on the user dashboard

### Current display
<img width="1111" alt="Screenshot 2024-11-06 at 11 14 24 AM" src="https://github.com/user-attachments/assets/0c99fdb9-9285-41e9-b1f5-8ebbe4997d30">

### Desired display
![383306301-ca9cd4e9-a568-4910-86eb-b9292ab40941](https://github.com/user-attachments/assets/42c08f97-2614-4662-a75c-2288e00fb541)

### Acceptance criteria
- [x] Request the data from Mediaflux
- [x] The quota and consumed storage are reflected in the UI with a bar graph as shown in Figma ([potential strategy here](https://css-tricks.com/making-charts-with-css/))
- [x] There is a test for this in the view

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/1030?planning-poker) with Zenhub @bess @carolyncole @JaymeeH @jrgriffiniii @leefaisonr
