### ISSUE TITLE
The `Directory Path` field should not be writable after it is approved

### ISSUE THREAD

**Issue by JaymeeH** [pulibrary/tigerdata-app#1046]
In Tigerdata, the edit form displays two fields `Project Directory` which is read only, and `Directory Path` which is writable. Editing the `Directory Path` and submitting the form updates both fields. Since both fields seem to be technically displaying the same information, It would make most sense to only display one and choose whether it is read only or read/write.

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlN5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65053812779cde09fa2b426799041abc0c2f0a8f/Screenshot%202024-11-12%20at%2010.20.11%E2%80%AFAM.png" alt="Screenshot 2024-11-12 at 10.20.11 AM.png" />

Acceptance Criteria:

- [ ] Data Sponsor should view the path, but not edit it
- [ ] Data Manager should view the path, but not edit it
- [ ] Data user should view the path, but not edit it
- [ ] System Administrator should view and edit  the path

**Comment by carolyncole** [comment]
Directory Path should be able to modify the directory path, but the data sponsor, manager, users should not be able to modify the path.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/1046?planning-poker) with Zenhub @hectorcorrea @leefaisonr @JaymeeH
