### ISSUE TITLE
[Spike] Can datatables be used on the dashboard for sub-projects

### ISSUE THREAD

**Issue by JaymeeH** [pulibrary/tigerdata-app#1061]
Investigate whether or not we can utilize datatables in order to achieve subprojects nested under parent projects on the Tigerdata Dashboard

reference : https://datatables.net/examples/api/row_details.html

Desired display:
![Kapture 2024-11-14 at 14 54 29](https://github.com/user-attachments/assets/83fd075d-b09b-4331-8276-545deebe2321)

**Comment by kelynch** [comment]
We can return the HTML that is needed instead of web components.  Closing this ticket.
