### ISSUE TITLE
Add tabbed navigation to the project page

### ISSUE THREAD

**Issue by kelynch** [pulibrary/tigerdata-app#1100]
Figma link: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=1325-22724&node-type=frame&t=etwn2DWmZNdNuUnP-0

Referenced in https://github.com/pulibrary/tigerdata-app/issues/1081

Add tabbed navigation to the project show page to navigate between sections as shown here:

<img width="898" alt="388791655-6e319aaa-7c62-4c33-aad1-050be3b5d280 (1)" src="https://github.com/user-attachments/assets/6004daec-4c21-48db-a4f7-302e15f4812b">

The tab below follows the same navigation format as the dashboard, referencing issue #7 , #15 

<img width="723" alt="Screenshot 2024-11-21 at 11 03 00 PM" src="https://github.com/user-attachments/assets/489f9110-625b-4b49-90e3-72a63a0a9452">

Mockup Figma Link: https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=1325-22724&t=MJxVuyRzH5BKs6pB-4

switch to dev mode for detailed spacing info and CSS code

## Acceptance criteria

- [ ] Remove all buttons except the "Approve" button from the bottom of the show page
- [x] There is tabbed navigation for "Content Preview" and "Details" only between sections of a project's show page
- [ ] There is a test for this

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/1100?planning-poker) with Zenhub @bess @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr

**Comment by carolyncole** [comment]
https://getbootstrap.com/docs/5.3/components/navs-tabs/
