### ISSUE TITLE
Remove the blue and yellow warning boxes after logging in

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tigerdata-app#1106]
### Expected behavior
See the blank bar...
![Screenshot 2024-12-11 at 8 05 37 AM](https://github.com/user-attachments/assets/e171076e-2f61-4f71-8f96-ac046ad6b048)

### Actual behavior
I would assume some text should be part of that bar.

### Steps to replicate

Login to tigerdata-staging.

### Impact of this bug
Does not look great

### Acceptance criteria
- [ ] The yellow and blue warning boxes are removed after login

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/1106?planning-poker) with Zenhub @bess @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr
