### ISSUE TITLE
Refresh the home page

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tigerdata-app#1113]
### Current display
![{59472C80-9479-40E1-A77A-0132F323E57D}](https://github.com/user-attachments/assets/0ce59a39-811f-463b-bfa5-2281d88a5094)

![{A62677CB-99F5-461F-B0D2-B35C1A9F450E}](https://github.com/user-attachments/assets/9ed100be-5ef0-4585-a3d4-3f90d1d4fa0a)

### Desired display
![{9E07BEBC-3938-4340-B036-41F06B9A1521}](https://github.com/user-attachments/assets/12a2f581-c61c-4f23-a4a1-edecef62b62c)

_For design details, go to Figma_: 
https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=2045-17449&m=dev

### Acceptance criteria
- [ ] The blue banners at the top can stay (both for the environment above the header and for messages below the banner)
- [ ] The login button is white, not yellow (as designed in Figma)
- [ ] The home page title reads "Welcome to TigerData Web Portal" (styled as designed in Figma)
- [ ] Below the title, there is the standard TigerData description text (styled as designed in Figma):

> TigerData is a data management service for the Princeton research community that includes a suite of software tools and scalable, tiered storage to enable the organization, description, storage, sharing, and long-term sustainability of research and administrative data.
It enables the things you want to do (with your data), and makes it easier to do the things you have to do.

- [ ] Below the description text there is a "Learn More" button (as designed in Figma), which goes to https://tigerdata.princeton.edu
- [ ] Below the "Learn More" button there is a note (as designed in Figma):

> Log in is currently limited to early adopters. Contact us for more information.

- [ ] The words "Contact us" in the note are a link to mailto:tigerdata@princeton.edu
- [ ] On the right side of the page is an image of a laptop showing the dashboard of the web app (as Designed in Figma)
- [ ] The yellow warning bar does not show upon logout when there is no message to display

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/1113?planning-poker) with Zenhub @bess @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr

**Comment by carolyncole** [comment]
The UI Ux folks said they were working on wire frames for this page.

**Comment by matthewjchandler** [comment]
@carolyncole I updated the ticket following discussions and design work with the AUX team.
