### ISSUE TITLE
Test projects in QA for key stakeholders

### ISSUE THREAD

**Issue by matthewjchandler** [pulibrary/tigerdata-app#1158]
Wind Cowles and Curt Hillegas would like to have test projects available to them in the QA environment, so they can explore the MVP functionality more.

### Completion Criteria

- [ ] Wind has three projects available to her: 1 as Data Sponsor, 1 as Data Manager, and 1 as Data User
- [ ] Curt has three projects available to him: 1 as Data Sponsor, 1 as Data Manager, and 1 as Data User
- [ ] All 6 of the above projects have some fixture data
- [ ] Matt Chandler is a Data User on all 6 of the above projects

**Comment by carolyncole** [comment]
running `bundle exec rake projects:create_small_project[<owner>,<name>]` six times
updating the projects in the console
```
project = Project.find(id)
project.title
project.metadata_model
project.metadata_model.data_sponsor = "user"
project.metadata_model.data_manager = "user"
project.metadata_model.data_user_read_only << "mjc12"
```

**Comment by carolyncole** [comment]
6 projects were added by running the rake task and adjusting the roles and then approving the project in the UI.  The approval process was needed before the size accumulator showed correctly.
