### ISSUE TITLE
Test ability for tiger-data-app to read from mediaflux in production

### ISSUE THREAD

**Issue by bess** [pulibrary/tigerdata-app#794]
## Acceptance criteria
- [ ] Select a real existing project in production for this test
- [ ] Review project metadata in Mediaflux (revise if needed)
- [ ] Set up project in presentation layer with accurate metadata
- [ ] Ensure information parity between the frontend and Mediaflux
- [ ] Data Manager is able to review project metadata and contents

**Comment by bess** [comment]
Sounds like this is on hold for now, until we can test out the CAS authentication system.

![Screenshot 2024-07-15 at 12 09 55 PM](https://github.com/user-attachments/assets/fa1d0447-d635-4797-9fd5-67aece6fc753)

**Comment by matthewjchandler** [comment]
We still need to sort out CAS integration, but the testing needs I envisioned with this ticket originally have changed. I'm going to close this one to clear it from the board, but Chuck and I may come up with new testing tickets after we have new developments with CAS integration.
