### ISSUE TITLE
Rename repo to tigerdata

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tigerdata-app#889]
All locations besides the application call tigerdata, tigerdata not tiger-data.

Completion criteria

- [x] Rename the repo
- [x] Update tower
- [x] update the readme/ docs as needed

**Comment by kelynch** [comment]
Can we rename this to `tigerdata-app` to differentiate it from the website, since this application's production URL will be `http://tigerdata-app.princeton.edu`?

**Comment by jrgriffiniii** [comment]
I have just a tested the deployment of the `main` branch into the `staging` environment using Tower and this is currently working.
