### ISSUE TITLE
Add Princeton authentication to mediaflux ansible build

### ISSUE THREAD

**Issue by bess** [pulibrary/tigerdata-app#902]
Use the document Robert Knight gave us and translate that into ansible so our systems match the RC systems as much as possible.

[Installation Steps for td-mf-db1.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmFmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1253a3e952d6702539ef8316da0afd6c6fb2d3b3/Installation%20Steps%20for%20td-mf-db1.docx)

[Configuring authentication_AD binding for Mediaflux.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmVmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d184802ecd07216cc6242a830ec4efb6590274b/Configuring%20authentication_AD%20binding%20for%20Mediaflux.docx)

### Notes

Try to add authentication based on the above notes.  Reach out to Robert Knight and Chuck Bentler with any questions regarding the notes.  The Operations Team has some expertise in adding Active Directory to ansible.  They could also be consulted.

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/902?planning-poker) with Zenhub @bess @carolyncole @JaymeeH @jrgriffiniii @leefaisonr
