### ISSUE TITLE
Create general tiger data service account

### ISSUE THREAD

**Issue by bess** [pulibrary/tigerdata-app#907]
We need a service account to connect to ldap. Register a service account with Kate as the sponsor. lib-tigerdata@princeton.edu might work.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/907?planning-poker) with Zenhub @bess @hectorcorrea @JaymeeH @leefaisonr
