### ISSUE TITLE
[Tiger Data/staging] NoMethodError: undefined method `[]' for nil

### ISSUE THREAD

**Issue by bess** [pulibrary/tigerdata-app#921]
This bug prevents project pages from rendering, and is blocking today's Tiger Data release.

## Backtrace

    line 96 of [PROJECT_ROOT]/app/controllers/projects_controller.rb: show
    line 21 of [PROJECT_ROOT]/app/controllers/application_controller.rb: mediaflux_session

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/113559/faults/110791705)

**Comment by kelynch** [comment]
Closing in favor of https://github.com/pulibrary/tigerdata-app/issues/924 per Feature Refinement discussion this morning.
