### ISSUE TITLE
Clean out the tiger data staging and QA server

### ISSUE THREAD

**Issue by bess** [pulibrary/tigerdata-app#924]
Many of the projects on tiger data staging pre-date our current expectations of projects (e.g., missing storage info) 

This is currently preventing tiger data v0.31.0 from working on our staging server, which is blocking our deployment pipeline. 

## Acceptance criteria
- [x] Ask Matt Chandler if this is okay (he says yes, per 18 September feature refinement meeting)
- [x] Tell research computing what we're about to do
- [ ] Clean out staging, front end and back end (using https://github.com/pulibrary/tigerdata-app/blob/main/lib/tasks/cleanup.rake)
- [x] Ask Matt Chandler if it is OK to clear out QA
- [x] Tell research computing what we're about to do
- [ ] Clean out QA, front end and back end (using https://github.com/pulibrary/tigerdata-app/blob/main/lib/tasks/cleanup.rake)

**Comment by kelynch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/924?planning-poker) with Zenhub @bess @carolyncole @hectorcorrea @jrgriffiniii @leefaisonr
