### ISSUE TITLE
Alignment on the project show page

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tigerdata-app#942]
### Current display
<img width="604" alt="Screenshot 2024-09-23 at 2 15 18 PM" src="https://github.com/user-attachments/assets/6dbd9489-4089-4848-a756-a97baac4acef">

### Desired display

Should be aligned

**Comment by matthewjchandler** [comment]
AUX is working on some mockups that address this, as part of the look and feel polishing effort.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/942?planning-poker) with Zenhub @hectorcorrea @JaymeeH @jrgriffiniii @leefaisonr
