### ISSUE TITLE
mediaflux_dev does not work with m2 chips

### ISSUE THREAD

**Issue by bess** [pulibrary/tigerdata-app#961]
### Expected behavior
Developers should be able to work on tiger data if they have a laptop with an M2 processor

### Actual behavior

![Screenshot 2024-09-30 at 10 52 20 AM](https://github.com/user-attachments/assets/d7d1da07-41ca-49b3-a29d-beed079e754a)

### Impact of this bug
Lauren, one of our student developers, cannot do her work. Also, if anyone gets a new laptop, they won't be able to do their work.

### Acceptance criteria
- [ ] The ansible build for the docker image allows for the building of an ARM image
- [ ] The instructions document how to use it

```
```

### Implementation notes, if any

We might need to pass in a new base image here  https://github.com/pulibrary/princeton_ansible/blob/main/playbooks/mflux-docker.yml#L8

**Comment by kelynch** [comment]
I have an M1, but I also experienced that error and was able to resolve it with the following:

```bash
docker create --name mediaflux --platform linux/amd64 --mac-address 02:42:ac:11:00:02 --publish 8888:80 pulibraryrdss/mediaflux_dev:latest
```

**Comment by hectorcorrea** [comment]
We could also consider downgrading the version of Docker that Lauren is using. We have seen that our docket container for Mediaflux does not work with newer versions of Docker.

Also, Jaymee confirmed that he has an M2 chip and has the Mediaflux Docker image working. We should check with him for specific versions.

**Comment by kelynch** [comment]
Another option would be to utilize the CI machine if none of the above ideas work.

**Comment by hectorcorrea** [comment]
Running the command that @kelynch indicated on (see above) did the trick for Lauren even with more recent version of Docker (4.30)

**Comment by hectorcorrea** [comment]
I can confirm that it also works with Docker 4.34.3 (on an old Mac with Intel chip)
