### ISSUE TITLE
Upgrade to rollup@^4.22.4 and other security upgrades

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/tigerdata-app#965]
### What maintenance needs to be done?

Make the upgrades requested in: https://github.com/pulibrary/tigerdata-app/security/dependabot

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
security

**Comment by kelynch** [comment]
Dependabot is making security updates for these.
