### ISSUE TITLE
Upgrade mediaflux to 4.16.071 in our ansible build

### ISSUE THREAD

**Issue by bess** [pulibrary/tigerdata-app#969]
### What maintenance needs to be done?

Upgrade mediaflux to 4.16.071 in our ansible build so we can match what RC is using. This version fixes the issue with NFS mounts.

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

## Acceptance critera

- [x] Create a new docker image with the newest version (Creates a fresh build, not upgrade the existing build)
- [ ] Assume the servers will be rebuilt when upgraded so no separate path is needed
- [ ] Created documentation on how to upgrade the version for docker
- [x] Let the team know so everyone can upgrade the local mediaflux image

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/969?planning-poker) with Zenhub @bess @JaymeeH @jrgriffiniii @kelynch @leefaisonr

**Comment by JaymeeH** [comment]
We are going to upgrade our docker build and server build separately.
