### ISSUE TITLE
Upgrade to rollup to 4.22.4

### ISSUE THREAD

**Issue by JaymeeH** [pulibrary/tigerdata-app#973]
- [x] yarn update rollup
- [x] Fix any failing tests or dependency issues caused by upgrade
- [x] Deploy code that works to staging
- [x] Manually test on staging box

**Comment by kelynch** [comment]
Check to see if this is already done.

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/973?planning-poker) with Zenhub @bess @JaymeeH @jrgriffiniii @leefaisonr @kelynch
