### ISSUE TITLE
Utility navigation / Profile component 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/tigerdata-app#983]
Part of header: https://github.com/pulibrary/tigerdata-app/issues/975 

**Update**

Header consists of TigerData logo (left), Contact Us, FAQ, and NetID (right), aligning in center. 
When click on the dropdown arrow next to user NetID, a menu appeared with [log out] option, in the future the menu should contain [Account Setting] or [User Profile] as well.

![Image](https://github.com/user-attachments/assets/e794fa30-6cd0-412f-b6d2-36d7ec7dcc32)

Detailed alignments in px (standard header width=1440px):

![Image](https://github.com/user-attachments/assets/8cd42b35-ae04-4f84-81a8-a71540521fef)
![Image](https://github.com/user-attachments/assets/055924a3-8bc1-4446-aa59-40003bbb39a2)

Figma Link: 
https://www.figma.com/design/rgzEYTpnGl6l68moRSVwYg/Phase-1-UI-Details?node-id=149-1623&m=dev

_Originally posted by @yiwenxx in https://github.com/pulibrary/aux/issues/6#issuecomment-2400398758_

Acceptance Criteria:

- [ ] The header has space where space is required, but it looks similar to the wireframe but not pixel exact.
- [ ] The header is responsive

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/983?planning-poker) with Zenhub @hectorcorrea @JaymeeH @leefaisonr @bess @kelynch

**Comment by carolyncole** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/983?planning-poker) with Zenhub @jrgriffiniii
