### ISSUE TITLE
Hide non-defined functions 

### ISSUE THREAD

**Issue by beth-german** [pulibrary/tigerdata-app#985]
Hide for production

- Withdraw project
- Deny project
- Custom query

Features in development or down the roadmap should not be displayed in production for release.

Previous issue: https://github.com/pulibrary/aux/issues/8 

Acceptance Critieria:

- [x] Remove Withdraw project button
- [x] Remove Deny project button
- [x] Remove Custom query button

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/tigerdata-app/985?planning-poker) with Zenhub @bess @hectorcorrea @JaymeeH @kelynch @leefaisonr @jrgriffiniii
